import sys 

class CustomExcetion(Exception):
    pass 